name: get_dsa
publish_to: none
dependencies:
  archive: "^1.0.19"
  polymer: "^0.16.3+3"
  core_elements: "^0.7.1+2"
  paper_elements: "^0.7.1"
  dslink:
    git: https://github.com/IOT-DSA/sdk-dslink-dart.git
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/packager.html
